'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Globalization
Imports System.Resources
Imports System.Runtime.CompilerServices

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     DebuggerNonUserCode(),  _
     CompilerGenerated(),  _
     HideModuleName()>  _
    Friend Module Resources
        
        Private resourceMan As ResourceManager
        
        Private resourceCulture As CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As ResourceManager
            Get
                If ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As ResourceManager = New ResourceManager("CodeChecker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botonAzul() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botonAzul", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botonAzul1() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botonAzul1", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botonGris() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botonGris", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botonRojo() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botonRojo", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BotonVerde() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonVerde", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BUTTON_BLUE() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_BLUE", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property GSE_7_SEGMENT_VFD() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("GSE_7_SEGMENT_VFD", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property LED_COUNTER_7() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("LED_COUNTER_7", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property LED_COUNTER_7_ITALIC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("LED_COUNTER_7_ITALIC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property led_Verde_OFF() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("led_Verde_OFF", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property right_or_wrong_2() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right-or-wrong-2", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property right_or_wrong_3() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right-or-wrong-3", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rojo_f01() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rojo_f01", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rojo_f02() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rojo_f02", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Verde_f01() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Verde_f01", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Verde_f02() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Verde_f02", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
    End Module
End Namespace
