'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.ComponentModel.Design
Imports System.Configuration
Imports System.Runtime.CompilerServices

Namespace My
    
    <CompilerGenerated(),  _
     GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     EditorBrowsable(EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <DebuggerNonUserCode(), EditorBrowsable(EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Object, e As EventArgs)
        If Application.SaveMySettingsOnExit Then
            Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("1000")>  _
        Public Property var_TOUT() As String
            Get
                Return CType(Me("var_TOUT"),String)
            End Get
            Set
                Me("var_TOUT") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("200")>  _
        Public Property var_TOn() As String
            Get
                Return CType(Me("var_TOn"),String)
            End Get
            Set
                Me("var_TOn") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("100")>  _
        Public Property var_TOFF() As String
            Get
                Return CType(Me("var_TOFF"),String)
            End Get
            Set
                Me("var_TOFF") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("100")>  _
        Public Property var_INTERVAL() As String
            Get
                Return CType(Me("var_INTERVAL"),String)
            End Get
            Set
                Me("var_INTERVAL") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property SKU() As String
            Get
                Return CType(Me("SKU"),String)
            End Get
            Set
                Me("SKU") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("1")>  _
        Public Property mode() As Integer
            Get
                Return CType(Me("mode"),Integer)
            End Get
            Set
                Me("mode") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <HideModuleName(),  _
     DebuggerNonUserCode(),  _
     CompilerGenerated()>  _
    Friend Module MySettingsProperty
        
        <HelpKeyword("My.Settings")>  _
        Friend ReadOnly Property Settings() As MySettings
            Get
                Return MySettings.Default
            End Get
        End Property
    End Module
End Namespace
